### ISSUE TITLE
when i created two sections with same name .. i am stuck with busy clock

### ISSUE THREAD

**Issue by riz-hossain** [AutomationSolutionz/Framework_0.1#356]
InterfaceError: cursor already closed
[30/Jan/2015 18:32:28] "GET /Home/ManageTestCases/setData/createSection/?section_text=tesd&project_id=PROJ-19&team_id=135 HTTP/1.1" 500 16280
[30/Jan/2015 18:32:32] "GET /Home/ManageTestCases/ HTTP/1.1" 200 53136
[30/Jan/2015 18:32:33] "GET /Home/ManageTestCases/GetProjectNameForTopBar/?user_id=9 HTTP/1.1" 200 100
[30/Jan/2015 18:32:33] "GET /Home/UserInfo/ServeProfilePictureURL/?username=riz&full_name=Riz+Hossain HTTP/1.1" 200 64
[30/Jan/2015 18:32:33] "GET /site_media/Jquery/jstree/jstree.min.js?_=1422660751762 HTTP/1.1" 200 90082
Internal Server Error: /Home/ManageTestCases/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Riz\git\Framework_0.1\Automationz\Framework_0.1\DjangoFramework\..\DjangoFramework\MySite\views.py", line 8341, in manage_test_cases
    temp['parent_text'] = section[-2]
IndexError: list index out of range
2015-01-30 18:32:33,194 ERROR Internal Server Error: /Home/ManageTestCases/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Riz\git\Framework_0.1\Automationz\Framework_0.1\DjangoFramework\..\DjangoFramework\MySite\views.py", line 8341, in manage_test_cases
    temp['parent_text'] = section[-2]
IndexError: list index out of range

**Comment by sazid** [comment]
The loading indicator may have a different issue.
But, I don't think we should allow sections with same name. There will be
conflicts as to where the child sections will be put when they're being
sent back from the server.

Think of this scenario:

• P1 > C1 > CA
• B2 > P1
• A4 > P1 > D3

Now, the computer won't know where to put P1 as the parent (row1) and where
to put P1 as the child (row 2, 3) because it traverses all rows during
calculation. Besides, rows in databases will not be ordered according to
sections. So, it is possible that, when a user has created another section
in between the sections with duplicate names, the computer won't be able to
traverse serially and hence, this issue can't be solved. This one will
require a bit more explanation. But, you should get the point.

**Comment by sazid** [comment]
7f717f1558b9473b4f234e4344adbde62a82bcde

**Comment by riz-hossain** [comment]
That's okay. I just to make sure I can do all the basic things. Create section, delete section, rename section and do the same with sub section. As long as duplicate name does not break things ,then it's okay. Make sure the other issue where it says db connection was not established is solved.   That's more important, because it blocks everything even in normal situation.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Mohammed Sazid-Al-RashidSent: Saturday, January 31, 2015 6:53 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] when i created two sections with same name .. i am stuck with busy clock (#356)7f717f1

—Reply to this email directly or view it on GitHub.

**Comment by sazid** [comment]
Should be resolved by now inshaAllah
